DROP DATABASE IF EXISTS app;
CREATE DATABASE IF NOT EXISTS app;
USE app;

CREATE TABLE User (
  `id` BINARY(16) DEFAULT (UUID_TO_BIN(UUID())) PRIMARY KEY,
  `username` varchar(255) UNIQUE NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` ENUM('patient', 'doctor') NOT NULL
);

CREATE TABLE Slot (
  `id` BINARY(16) DEFAULT (UUID_TO_BIN(UUID())) PRIMARY KEY,
  `start` TIMESTAMP NOT NULL,
  `end` TIMESTAMP NOT NULL,
  doctorId BINARY(16) NOT NULL,
  patientId BINARY(16) DEFAULT NULL,
  CONSTRAINT FK_SLOT_DOCTOR FOREIGN KEY (doctorId) REFERENCES User(id) ON DELETE CASCADE,
  CONSTRAINT FK_SLOT_PATIENT FOREIGN KEY (patientId) REFERENCES User(id)
);
