volumes:
  t3p-database:
    external: false
  t3p-messaging:
    external: false

services:
  t3p-frontend:
    build: ./frontend
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    environment:
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - t3p-backend
    expose:
      - "${FRONTEND_PORT}"
  t3p-backend:
    hostname: ${BACKEND_HOST}
    build: ./backend
    depends_on:
      t3p-database:
        condition: service_healthy
      t3p-messaging:
        condition: service_started
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - MESSAGING_HOST=${MESSAGING_HOST}
      - MESSAGING_PORT=${MESSAGING_PORT}
    expose:
      - "${BACKEND_PORT}"
  t3p-database:
    hostname: ${MYSQL_HOST}
    build: ./db
    volumes:
      - t3p-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=app
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_PORT}
    expose:
      - "${MYSQL_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "${MYSQL_HOST}"]
      interval: 5s
      timeout: 10s
      retries: 10
  t3p-messaging:
    hostname: ${MESSAGING_HOST}
    build: ./messaging
    volumes:
      - t3p-messaging:/data
    command: --port ${MESSAGING_PORT}
    expose:
      - "${MESSAGING_PORT}"
