volumes:
  database:
    external: false

services:
  frontend:
    container_name: frontend
    image: frontend
    build: ./frontend
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    depends_on:
      - backend
  backend:
    container_name: backend
    image: backend
    build: ./backend
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    depends_on:
      database:
        condition: service_healthy
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
  database:
    container_name: database
    image: database
    build: ./db
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=app
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "database"]
      interval: 5s
      timeout: 10s
      retries: 10
