volumes:
  backend_builder_packages:
    external: false

services:
  backend_builder:
    container_name: backend_builder
    image: golang:1.21.3-alpine3.18
    network_mode: bridge
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_builder_packages:/go/pkg
    command: /bin/sh -c "go get . && exec go build -o bin/backend"
