services:
  t3p-backend-test:
    container_name: t3p-backend-test
    image: t3p-backend-test
    build: ./backend-tests
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - src_t3p-api-network

networks:
  src_t3p-api-network:
    external: true
